import { StyleSheet } from "@react-pdf/renderer";

export const pdfStyles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 10,
    fontFamily: "Helvetica",
    color: "#1a1a1a",
  },
  coverHeader: {
    backgroundColor: "#1E3A5F",
    color: "#ffffff",
    padding: 20,
    marginBottom: 24,
    textAlign: "center",
  },
  coverTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 6,
  },
  coverSubtitle: {
    fontSize: 11,
    opacity: 0.95,
  },
  coverRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e5e5",
    paddingBottom: 6,
  },
  coverLabel: { fontSize: 9, color: "#555", width: "38%" },
  coverValue: { fontSize: 10, fontWeight: "bold", width: "60%" },
  sectionHeader: {
    backgroundColor: "#F0F0F0",
    padding: 10,
    marginBottom: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  sectionTitle: { fontSize: 13, fontWeight: "bold", color: "#1E3A5F" },
  sectionMeta: { fontSize: 9, color: "#666" },
  itemRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 5,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  itemLabel: { width: "48%", fontSize: 9 },
  itemValue: { width: "48%", fontSize: 9, textAlign: "right" },
  good: { color: "#1e7a34" },
  repair: { color: "#c82333" },
  muted: { color: "#666" },
  observation: {
    fontSize: 8,
    color: "#555",
    fontStyle: "italic",
    marginLeft: 8,
    marginTop: 2,
    marginBottom: 6,
  },
  photoRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 6,
    marginBottom: 10,
  },
  photoThumbWrap: {
    marginRight: 8,
    marginBottom: 8,
  },
  photoThumb: {
    width: 140,
    height: 105,
    objectFit: "cover",
  },
  footerTitle: { fontSize: 12, fontWeight: "bold", marginBottom: 10 },
  disclaimer: {
    fontSize: 8,
    lineHeight: 1.35,
    color: "#444",
    textAlign: "justify",
  },
  galleryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  galleryCell: { width: "48%", marginBottom: 12 },
  galleryImg: { width: "100%", height: 140, objectFit: "cover" },
  galleryCap: { fontSize: 8, marginTop: 4, color: "#555" },
  pageHeader: {
    fontSize: 8,
    color: "#888",
    marginBottom: 12,
    textAlign: "right",
  },
});
