import { StyleSheet } from "@react-pdf/renderer";

export const pdfStyles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 10,
    fontFamily: "Helvetica",
    color: "#1a1a1a",
  },
  coverHeader: {
    backgroundColor: "#1E3A5F",
    color: "#ffffff",
    padding: 20,
    marginBottom: 24,
    textAlign: "center",
  },
  coverTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 6,
  },
  coverSubtitle: {
    fontSize: 11,
    opacity: 0.95,
  },
  /** Portada inicial (solo título + inspector). */
  coverPage: {
    padding: 48,
    fontFamily: "Helvetica",
    color: "#1a1a1a",
    flexDirection: "column",
  },
  coverPageBody: {
    flexGrow: 1,
    justifyContent: "center",
  },
  coverPageInner: {
    alignItems: "center",
    paddingVertical: 24,
  },
  coverPageBrand: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#1E3A5F",
    marginBottom: 8,
    textAlign: "center",
  },
  coverPageReportTitle: {
    fontSize: 14,
    color: "#333",
    textAlign: "center",
    marginBottom: 36,
    lineHeight: 1.4,
  },
  coverPageInspectorBlock: {
    marginTop: 8,
    alignItems: "center",
    maxWidth: "100%",
  },
  coverPageInspectorLine: {
    fontSize: 11,
    color: "#333",
    textAlign: "center",
    lineHeight: 1.5,
  },
  coverPageInspectorName: {
    fontSize: 13,
    fontWeight: "bold",
    color: "#1a1a1a",
    marginTop: 6,
    textAlign: "center",
  },
  coverPageOrderFooter: {
    fontSize: 8,
    color: "#888",
    textAlign: "center",
    marginTop: 12,
  },
  coverRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e5e5",
    paddingBottom: 6,
  },
  coverLabel: { fontSize: 9, color: "#555", width: "38%" },
  coverValue: { fontSize: 10, fontWeight: "bold", width: "60%" },
  sectionHeader: {
    backgroundColor: "#F0F0F0",
    padding: 10,
    marginBottom: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  sectionTitle: { fontSize: 13, fontWeight: "bold", color: "#1E3A5F" },
  sectionMeta: { fontSize: 9, color: "#666" },
  itemRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 5,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  itemLabel: { width: "48%", fontSize: 9 },
  itemValue: { width: "48%", fontSize: 9, textAlign: "right" },
  good: { color: "#1e7a34" },
  repair: { color: "#c82333" },
  muted: { color: "#666" },
  observation: {
    fontSize: 8,
    color: "#555",
    fontStyle: "italic",
    marginLeft: 8,
    marginTop: 2,
    marginBottom: 6,
  },
  photoRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 6,
    marginBottom: 10,
  },
  photoThumbWrap: {
    marginRight: 8,
    marginBottom: 8,
  },
  photoThumb: {
    width: 140,
    height: 105,
    objectFit: "cover",
  },
  footerTitle: { fontSize: 12, fontWeight: "bold", marginBottom: 10 },
  disclaimer: {
    fontSize: 8,
    lineHeight: 1.35,
    color: "#444",
    textAlign: "justify",
  },
  galleryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  galleryCell: { width: "48%", marginBottom: 12 },
  /**
   * Galería final / hallazgos: `contain` para no recortar (antes `cover` en caja ~2:1
   * cortaba más que los thumbs 4:3 de portada).
   */
  galleryImg: {
    width: "100%",
    height: 160,
    objectFit: "contain",
    backgroundColor: "#f5f5f5",
  },
  galleryCap: { fontSize: 8, marginTop: 4, color: "#555" },
  pageHeader: {
    fontSize: 8,
    color: "#888",
    marginBottom: 12,
    textAlign: "right",
  },
  summaryExecutiveTitle: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#1E3A5F",
    marginBottom: 6,
  },
  summarySubtitle: {
    fontSize: 9,
    color: "#555",
    lineHeight: 1.35,
    marginBottom: 12,
  },
  summaryTotalLine: {
    fontSize: 10,
    fontWeight: "bold",
    marginBottom: 10,
    paddingVertical: 6,
    paddingHorizontal: 8,
    backgroundColor: "#f5f5f5",
    borderRadius: 4,
  },
  summarySectionTag: {
    fontSize: 8,
    fontWeight: "bold",
    color: "#1E3A5F",
    marginBottom: 2,
    textTransform: "uppercase",
  },
  summaryFindingBlock: {
    marginBottom: 10,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  summaryPhotoTitle: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#1E3A5F",
    marginBottom: 10,
  },
});
